### ISSUE TITLE
[RFE] Expand compatibility, test on Firefox/Palemoon/Iceweasel

### ISSUE THREAD

**Issue by Atavic** [keeganjk/smokescreen#2]
Great idea, @keeganjk, as obfuscation is a must with the current lack of anonimity options.

Tried on Firefox 52.0 ESR and it does appear to work, but the pages load with a timelapse that's too fast.

**Comment by keeganjk** [comment]
Thanks for the feedback! I've now edited the code so that it will work with Chrome, Firefox, and Microsoft Edge. Next, I plan to make it compatible with Safari, Opera, and maybe even Vivaldi!

I've also added a place in the script where you can adjust the number of milliseconds between each page close, so you can adjust the speed of the script.
